### ISSUE TITLE
Add BIG RED WARNING for unverified smart contracts

### ISSUE THREAD

**Issue by luke7211** [l2beat/l2beat#833] opened 2022-10-17 11:08 UTC
This issue is self-explanatory. Contracts should be verified, otherwise users are essentially throwing funds into the black box. We may not like it but Etherscan, while admittedly centralized, is a de-facto standard for contract verification on Ethereum. Teams should strive to make sure their contracts are transparent and verified there. If other verification method is used, l2beat team can always be contacted directly to rectify the issue.

**Comment by krzkaczor** [comment] 2022-11-02 10:09
Closing in favour of linear. Duplicate of #225

**Closed by krzkaczor** 2022-11-02 10:09 UTC
